version: "3"

services:
  todo-cache-ingestion:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-cache-ingestion:latest

  todo-cache-service:
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-cache-service:latest
    

  todo-search-ingestion:
    
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-search-ingestion:latest
    command: sh /home/node/app/start.sh
    

  todo-search-service:
    
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-search-service:latest
    command: sh /home/node/app/start.sh
    
  todo-storage-ingestion:
    
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-storage-ingestion:latest
    command: sh /home/node/app/start.sh
    
  todo-storage-service:
    
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-storage-service:latest
    
  todo-api-gateway:
    
    build:
      
      dockerfile: ../Dockerfile.nodejs.prod
    image: manomit/todo-api-gateway:latest
    command: sh /home/node/app/start.sh
    
  todo-view:
    
    build:
      
      dockerfile: Dockerfile.prod
    image: manomit/todo-view:latest
    ports: 
        - 4201:8080
  todo-proxy:
    image: manomit/todo-proxy:latest
